### ISSUE TITLE
node 12 deprecation

### ISSUE THREAD

**Issue by ynixon** [browser-actions/setup-firefox#346]
I'm getting this warning:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: browser-actions/setup-firefox, browser-actions/setup-geckodriver

Solution: Upgrade to Node.js 16.

Additional context
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by pkasarda** [comment]
there is open PR for this https://github.com/browser-actions/setup-firefox/pull/341
