### ISSUE TITLE
Node20 Support

### ISSUE THREAD

**Issue by ataylormays-duetto** [browser-actions/setup-firefox#519]
GitHub Actions is deprecating support for Node16 and encouraging a migration to Node20. Running the current version of `setup-firefox` results in the following warning:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: browser-actions/setup-firefox@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by ueokande** [comment]
Closed by https://github.com/browser-actions/setup-firefox/pull/520
