### ISSUE TITLE
Unsupported platform macos arm64 for version latest

### ISSUE THREAD

**Issue by david-dick** [browser-actions/setup-firefox#545]
When using setup-firefox as a github action, I get the following error

Error: Unsupported platform macos arm64 for version latest

This looks to be related to https://github.com/orgs/community/discussions/102846 for the release of macos-14

with snippets from the github workflow

```
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
        firefox: [ 'latest-beta', 'latest' ] # 'latest-devedition', 'latest-esr',
```

**Comment by ueokande** [comment]
Closed by #546. Thank you for your report.
